# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'

variables:
  - group: aws_ecr
  - group: aws_eks
  - group: github_token
  - group: SLACK_WEBHOOK
  - name: IMAGE_TAG
    value: $(Build.BuildId)

stages:

- stage: Test
  displayName: Run Unit & Integration Tests
  jobs:
    - job: TestJob
      steps:

        - script: |
            echo "Installing dependencies..."
            npm install
          workingDirectory: project/app
          displayName: "Install Dependencies"

        - script: |
            echo "Installing test framework..."
            npm install --save-dev jest supertest
          workingDirectory: project/app
          displayName: "Install Test Tools"

        - script: |
            echo "Running tests..."
            npm test
          workingDirectory: project/app
          displayName: "Run Tests"

        - script: |
            echo "Dependency security scan..."
            trivy fs --severity HIGH,CRITICAL .
          workingDirectory: project/app
          displayName: "Dependency Scan"


- stage: BuildScanPush
  displayName: Build, Scan and Push Docker Image
  jobs:
    - job: BuildScanPushJob
      steps:

        - script: |
            echo "Login to ECR"
            aws ecr get-login-password --region "$(AWS_REGION)" | \
            docker login --username AWS --password-stdin "$(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com"
          displayName: "ECR Login"

        - script: |
            echo "Build image"
            docker build -t $(AWS_ECR_REGISTRY):app-$(IMAGE_TAG) -f project/Dockerfile project
          displayName: "Docker Build"

        - script: |
            echo "Scan image"
            trivy image  --severity HIGH,CRITICAL $(AWS_ECR_REGISTRY):app-$(IMAGE_TAG)
          displayName: "Scan Image"

        - script: |
            echo "Push image"
            docker push $(AWS_ECR_REGISTRY):app-$(IMAGE_TAG)
          displayName: "Push Image"
         

- stage: terraform
  displayName: Deploy Infrastructure with Terraform
  jobs:
    - job: TerraformJob
      steps:
        - script: |
            echo "Terraform Init"
            terraform init
          workingDirectory: infrastructure  
          displayName: "Terraform Init"
        - script: |
            echo "Terraform plan"
            terraform plan 
          workingDirectory: infrastructure  
          displayName: "Terraform Plan"
        - script: | 
            echo "Terraform apply"     
            terraform apply -auto-approve 
          workingDirectory: infrastructure
          displayName: "Terraform Apply"

     
- stage: CodePush
  displayName: Update ArgoCD Repo
  dependsOn: BuildScanPush

  jobs:
    - deployment: PushToArgoCD   
      displayName: Push to GitOps Repo
      environment: argocd-approval   

      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              - script: |
                  echo "Using IMAGE_TAG = $(IMAGE_TAG)"

                  echo "Cloning ArgoCD Repo..."
                  git clone https://$(GITHUB_TOKEN)@github.com/krishnamoorthyrajendran/OctaByte-assignment-CD.git cd-repo

                  echo "Updating Deployment YAML..."
                  sed -i "s|image: .*|image: $(AWS_ECR_REGISTRY):app-$(IMAGE_TAG)|" cd-repo/k8s/deployment.yaml

                  cd cd-repo

                  git config user.email "krishnamoorthy980@gmail.com"
                  git config user.name "krishnamoorthy"

                  git add .
                  git commit -m "Update image to $(AWS_ECR_REGISTRY):app-$(IMAGE_TAG)"
                  git push
                displayName: "Update GitOps Repo"

- stage: NotifyFailure
  displayName: Slack Notification
  condition: succeeded()
  jobs:
    - job: Notify
      steps:
        - script: |
            curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"✅ Pipeline Succeeded: $(Build.DefinitionName) | Build $(Build.BuildId)\"}" \
            $(SLACK_WEBHOOK_URL)
          displayName: "Send Slack Alert"
          