# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'

variables:
  - group: aws_ecr
  - name: IMAGE_TAG
    value: $(Build.BuildId)

stages:

- stage: Test
  displayName: Run Unit & Integration Tests
  jobs:
    - job: TestJob
      steps:
        - script: |
            echo "Installing dependencies..."
            npm install

            echo "Running unit + integration tests..."
            npm test
          workingDirectory: project/app
          displayName: "Run Tests"

        - script: |
            echo "Dependency security scan..."
            trivy fs --severity HIGH,CRITICAL .
          workingDirectory: project/app
          displayName: "Dependency Scan"


- stage: BuildScanPush
  jobs:
    - job: BuildScanPushJob
      steps:
        - script: |
            echo "Login to ECR"
            aws ecr get-login-password --region "$(AWS_REGION)" | \
            docker login --username AWS --password-stdin "$(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com"

            echo "Build images"
            docker build -t $(AWS_ECR_REGISTRY):app-$(IMAGE_TAG) -f project/Dockerfile .
          workingDirectory: project

            echo "Scan images"
            trivy image --exit-code 1 --severity HIGH,CRITICAL $(AWS_ECR_REGISTRY):app-$(IMAGE_TAG)
           

            echo "Push images"
            docker push $(AWS_ECR_REGISTRY):app-$(IMAGE_TAG)
           
          displayName: 'Build, Scan, and Push Docker Images'
         



